### ISSUE TITLE
泛化调用问题

### ISSUE THREAD

**Issue by pkeke** [KevinClair/Ymir#1]
您好！看了您的代码有点疑问想请教一下您，您写的泛化调用实现，我看到需要把入参的全限定名转化为对应的class类型，但即然是泛化调用，对应接口的入参类型不一定在客户端有实现啊！

**Comment by KevinClair** [comment]
客户端需要知道接口的参数类型，传递给服务端，服务端会根据参数类型找到对应的class

**Comment by KevinClair** [comment]
抱歉才看到这个issue，很久没更新这个项目了。
